### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by Raigen** [coursera/scribe-plugin-placeholder#2]
Can you please provide the plugin on npm, too?
We would like to use it, but we switched all our bower dependencies to npm a couple of month ago. It is much easier when requireing packages in nodejs and webpack.

**Comment by jnwng** [comment]
done: https://www.npmjs.com/package/scribe-plugin-placeholder

thanks for reaching out!

**Comment by ankit** [comment]
thanks for publishing @jnwng

**Comment by Raigen** [comment]
thanks a lot!
